name: expense_tracker_backend
description: Local Shelf backend for expense tracker storage
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  shelf_static: ^1.1.2

executables:
  expense-backend: bin/server.dart
